Correction pour prise en compte de differents repertoires sources de linux, et desactivation du SSP (bugs sortis avec 1.4.à-beta2

diff --git a/audela/src/configure b/audela/src/configure
--- a/audela/src/configure
+++ b/audela/src/configure
@@ -5551,8 +5551,21 @@ _ACEOF
 
 fi
 
+{ echo "$as_me:$LINENO: checking for kernel headers" >&5
+echo $ECHO_N "checking for kernel headers... $ECHO_C" >&6; }
 if test ! -f /usr/include/asm/system.h ; then
+    if test -f /usr/src/linux-headers-`uname -r`/include/asm/system.h ; then
         CXXFLAGS+="-I /usr/src/linux-headers-`uname -r`/include "
+        msg="yes (/usr/src/linux-headers-`uname -r`)"
+        { echo "$as_me:$LINENO: result: $msg" >&5
+echo "${ECHO_T}$msg" >&6; }
+    fi
+    if test -f /usr/src/linux-`uname -r`/include/asm/system.h ; then
+        CXXFLAGS+="-I /usr/src/linux-`uname -r`/include "
+        msg="yes (/usr/src/linux-`uname -r`)"
+        { echo "$as_me:$LINENO: result: $msg" >&5
+echo "${ECHO_T}$msg" >&6; }
+    fi
 fi
 
 WEBCAM_ENABLE=1
@@ -6138,6 +6151,148 @@ if test $TARGET = "Linux"; then
 fi
 
 
+
+
+  ssp_cc=yes
+  if test "X$CC" != "X"; then
+    { echo "$as_me:$LINENO: checking whether ${CC} accepts -fno-stack-protector" >&5
+echo $ECHO_N "checking whether ${CC} accepts -fno-stack-protector... $ECHO_C" >&6; }
+    ssp_old_cflags="$CFLAGS"
+    CFLAGS="$CFLAGS -fno-stack-protector"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ssp_cc=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+    echo $ssp_cc
+    if test "X$ssp_cc" = "Xno"; then
+      CFLAGS="$ssp_old_cflags"
+    fi
+  fi
+
+
+  ssp_cxx=yes
+  if test "X$CXX" != "X"; then
+    { echo "$as_me:$LINENO: checking whether ${CXX} accepts -fno-stack-protector" >&5
+echo $ECHO_N "checking whether ${CXX} accepts -fno-stack-protector... $ECHO_C" >&6; }
+    ssp_old_cxxflags="$CXXFLAGS"
+    CXXFLAGS="$CXXFLAGS -fno-stack-protector"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ssp_cxx=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+    echo $ssp_cxx
+    if test "X$ssp_cxx" = "Xno"; then
+	CXXFLAGS="$ssp_old_cxxflags"
+    fi
+  fi
 
 
 
